# Site settings
author: Brandon
title: MY path Through Flatiron
header-img: img/home-bg.png
email: brandon.james414@gmail.com
copyright_name: Brandon
description: > # this means to ignore newlines until "baseurl:"
  school
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Brandon0716

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
